rmq: # message bus
  host: "144.76.238.25" #amqps
  port: "5672"
  vhost: "/"
  username: "linkuser"
  password: "Ov3rw4tch"
  ssl: true
ckan:
  url: "https://ckan.terra-sense.eu"
  app_project: "engineering"
  organization_email: "ads@linksfoundation.com"
  organization_name: "LINKS Foundation"
  auth:
    url: "https://overwatch.terra-sense.eu/keycloak/realms/ckan-realm/protocol/openid-connect/token"
    username: "mario"
    password: "mario"
    client_id: "overwatch-partner"
    client_secret: "X6GqQ4J6WIhK63thoqgIkU1o5lJ8AuLZ"
    api_key: "ca71207f-732d-4b96-840a-a11d20ffb812"
nodeodm:
  host: "localhost"
  port: 3000
  token: "tbd"
